### ISSUE TITLE
つくばチャレンジの環境地図, waypoinsの管理方法について

### ISSUE THREAD

**Issue by shunki1006** [KBKN-Autonomous-Robotics-Lab/kbkn_maps#10]
現状kbkn_mapsではmaps, waypoints双方のつくばファイルを日付のフォルダで管理しています. 
しかし, 現在の命名規則(日付_チーム名)では確認走行と公園内の地図の名前が被ってしまい, 分かりにくくなる可能性があります. 
いつのファイルかよりもなんのファイルかがわかった方が使いやすいと思います. 

そこで, ①tsukubaのフォルダ内に確認走行, 信号機, 公園内のフォルダを作る. 
または, ②ファイルの命名規則を変更し, traffic_light_Senior.yamlのようにどのファイルなのかがわかるようにする. 
または, ③その両方などで管理する. 
上記のように変更した方が良いのではないででしょうか. 

上記のような管理方法に変更したい所存です. ご意見お願いします.

**Comment by shunki1006** [comment]
@Alpaca-zip @koki0624 ご意見お願いいたします.

**Comment by koki0624** [comment]
個人的には、ディレクトリの階層が多重になるほどパスが長くなってしまうので、tsukuba/m2/ の下でファイル名による管理がいいかなと思います。

もう一点、地図とウェイポイントは基本的に1対1で対応するはずなので、例えば

maps/tsukuba/m2/park1.yaml (.pgm)
waypoints/tsukuba/m2/park1.yaml

のように、maps/ と waypoints/ から下のパスを同じにすると、launch しやすいかもしれません。
以下のようなイメージです。
```xml
<launch>
    <arg name="file_path"  default="tsukuba/m2/park1.yaml"/>  <!-- ここを指定してlaunch -->
    
    <arg name="map_file"        default="$(find-pkg-share kbkn_maps)/maps/$(var file_path)"/>
    <arg name="waypoints_file"  default="$(find-pkg-share kbkn_maps)/waypoints/$(var file_path)"/>
...
```

**Comment by shunki1006** [comment]
> 個人的には、ディレクトリの階層が多重になるほどパスが長くなってしまうので、tsukuba/m2/ の下でファイル名による管理がいいかなと思います。
> 
> もう一点、地図とウェイポイントは基本的に1対1で対応するはずなので、例えば
> 
> maps/tsukuba/m2/park1.yaml (.pgm) waypoints/tsukuba/m2/park1.yaml
> 
> のように、maps/ と waypoints/ から下のパスを同じにすると、launch しやすいかもしれません。 以下のようなイメージです。
> 
> ```
> <launch>
>     <arg name="file_path"  default="tsukuba/m2/park1.yaml"/>  
>     
>     <arg name="map_file"        default="$(find-pkg-share kbkn_maps)/maps/$(var file_path)"/>
>     <arg name="waypoints_file"  default="$(find-pkg-share kbkn_maps)/waypoints/$(var file_path)"/>
> ...
> ```

良いですね, これにしましょう.

**Comment by shunki1006** [comment]
> 個人的には、ディレクトリの階層が多重になるほどパスが長くなってしまうので、tsukuba/m2/ の下でファイル名による管理がいいかなと思います。
> 
> もう一点、地図とウェイポイントは基本的に1対1で対応するはずなので、例えば
> 
> maps/tsukuba/m2/park1.yaml (.pgm) waypoints/tsukuba/m2/park1.yaml
> 
> のように、maps/ と waypoints/ から下のパスを同じにすると、launch しやすいかもしれません。 以下のようなイメージです。
> 
> ```
> <launch>
>     <arg name="file_path"  default="tsukuba/m2/park1.yaml"/>  
>     
>     <arg name="map_file"        default="$(find-pkg-share kbkn_maps)/maps/$(var file_path)"/>
>     <arg name="waypoints_file"  default="$(find-pkg-share kbkn_maps)/waypoints/$(var file_path)"/>
> ...
> ```

この方法を採用した形でpushしておきました, ご確認お願いいたします. 
@koki0624 @Alpaca-zip

**Comment by shunki1006** [comment]
> > 個人的には、ディレクトリの階層が多重になるほどパスが長くなってしまうので、tsukuba/m2/ の下でファイル名による管理がいいかなと思います。
> > もう一点、地図とウェイポイントは基本的に1対1で対応するはずなので、例えば
> > maps/tsukuba/m2/park1.yaml (.pgm) waypoints/tsukuba/m2/park1.yaml
> > のように、maps/ と waypoints/ から下のパスを同じにすると、launch しやすいかもしれません。 以下のようなイメージです。
> > ```
> > <launch>
> >     <arg name="file_path"  default="tsukuba/m2/park1.yaml"/>  
> >     
> >     <arg name="map_file"        default="$(find-pkg-share kbkn_maps)/maps/$(var file_path)"/>
> >     <arg name="waypoints_file"  default="$(find-pkg-share kbkn_maps)/waypoints/$(var file_path)"/>
> > ...
> > ```
> 
> この方法を採用した形でpushしておきました([fix_maps(waypoints)/tsukuba/m1(m2)/xxx.yaml](https://github.com/KBKN-Autonomous-Robotics-Lab/kbkn_maps/commit/a6cf03c344dcebe7fea35d1fe404b00fa13673b5)), ご確認お願いいたします. @koki0624 @Alpaca-zip
